/**
 * ERI Photography Library
 * ========================
 * Curated Unsplash images aligned to the ERI brand photography principles:
 * - Documentary / systemic / human-scale
 * - Full colour, no filters or overlays
 * - Aerial/overhead for chapter openers; wide establishing for section dividers;
 *   human-scale detail for case studies
 *
 * Each image has a stable reference ID (e.g. ERI-OPS-001) that can be used in
 * Manus AI task prompts: "Use photo ERI-OPS-001 from the ERI Brand Design System."
 *
 * Unsplash images are free to use under the Unsplash Licence.
 * For publication, prefer Alamy or Shutterstock licensed equivalents.
 *
 * Image dimensions: 1200×800 (3:2) via Unsplash API parameters.
 */

export interface EriPhoto {
  id: string;           // Stable reference ID, e.g. "ERI-OPS-001"
  unsplashId: string;   // Unsplash photo ID for direct URL construction
  url: string;          // Full Unsplash URL at 1200×800
  thumb: string;        // Thumbnail at 400×267
  alt: string;          // Descriptive alt text
  pillar: string;       // Pillar category or "Brand"
  pillarNum: number | null; // 1–5 or null for Brand
  subject: string;      // Short subject description
  composition: "aerial" | "wide" | "human-scale"; // Composition type
  keywords: string[];   // Search keywords for AI task use
  credit: string;       // Photographer name on Unsplash
}

export const photoLibrary: EriPhoto[] = [
  // ── BRAND / GENERAL ──────────────────────────────────────────────────────
  {
    id: "ERI-BRD-001",
    unsplashId: "XMFZqrGyV-Q",
    url: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=400&h=267&fit=crop",
    alt: "Aerial view of a mountain valley with winding river — systemic landscape",
    pillar: "Brand",
    pillarNum: null,
    subject: "Mountain valley aerial — systemic landscape",
    composition: "aerial",
    keywords: ["landscape", "aerial", "nature", "systemic", "roadmap"],
    credit: "Sergei Akulich",
  },
  {
    id: "ERI-BRD-002",
    unsplashId: "JpflvuBZ-8U",
    url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400&h=267&fit=crop",
    alt: "Aerial view of a foggy forest — scale and complexity of natural systems",
    pillar: "Brand",
    pillarNum: null,
    subject: "Foggy forest aerial — natural systems at scale",
    composition: "aerial",
    keywords: ["forest", "aerial", "fog", "nature", "systems"],
    credit: "Lukasz Szmigiel",
  },
  {
    id: "ERI-BRD-003",
    unsplashId: "Q1p7bh3SHj8",
    url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&h=267&fit=crop",
    alt: "Wide view of a city skyline at dusk — urban scale and infrastructure",
    pillar: "Brand",
    pillarNum: null,
    subject: "City skyline at dusk — urban infrastructure",
    composition: "wide",
    keywords: ["city", "skyline", "urban", "infrastructure", "scale"],
    credit: "Pedro Lastra",
  },
  {
    id: "ERI-BRD-004",
    unsplashId: "vHnVtLK8rCc",
    url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=267&fit=crop",
    alt: "Aerial view of a highway interchange — systemic infrastructure",
    pillar: "Brand",
    pillarNum: null,
    subject: "Highway interchange aerial — systemic infrastructure",
    composition: "aerial",
    keywords: ["highway", "infrastructure", "aerial", "systemic", "transport"],
    credit: "Denys Nevozhai",
  },

  // ── PILLAR 1: CUT OPERATIONAL EMISSIONS ──────────────────────────────────
  {
    id: "ERI-OPS-001",
    unsplashId: "Q6UehpkBCnI",
    url: "https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=400&h=267&fit=crop",
    alt: "Solar panel array on a factory rooftop — operational renewable energy",
    pillar: "Pillar 1 – Operations",
    pillarNum: 1,
    subject: "Solar panels on factory roof — operational renewables",
    composition: "wide",
    keywords: ["solar", "factory", "renewable", "energy", "operational"],
    credit: "American Public Power Association",
  },
  {
    id: "ERI-OPS-002",
    unsplashId: "8Gg2Ne_uTcM",
    url: "https://images.unsplash.com/photo-1548337138-e87d889cc369?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1548337138-e87d889cc369?w=400&h=267&fit=crop",
    alt: "Wind turbines in a field — clean energy generation at scale",
    pillar: "Pillar 1 – Operations",
    pillarNum: 1,
    subject: "Wind turbines in field — clean energy at scale",
    composition: "wide",
    keywords: ["wind", "turbines", "energy", "clean", "renewable"],
    credit: "Nicholas Doherty",
  },
  {
    id: "ERI-OPS-003",
    unsplashId: "7JX0-bfiuxQ",
    url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&h=267&fit=crop",
    alt: "Engineer checking equipment in a data centre — operational efficiency",
    pillar: "Pillar 1 – Operations",
    pillarNum: 1,
    subject: "Engineer in data centre — operational efficiency",
    composition: "human-scale",
    keywords: ["data centre", "engineer", "efficiency", "operations", "technology"],
    credit: "ThisisEngineering",
  },
  {
    id: "ERI-OPS-004",
    unsplashId: "ND3_KBwEFqk",
    url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&h=267&fit=crop",
    alt: "Aerial view of solar farm — large-scale renewable energy deployment",
    pillar: "Pillar 1 – Operations",
    pillarNum: 1,
    subject: "Solar farm aerial — large-scale renewable deployment",
    composition: "aerial",
    keywords: ["solar farm", "aerial", "renewable", "scale", "energy"],
    credit: "Zbynek Burival",
  },
  {
    id: "ERI-OPS-005",
    unsplashId: "pMnw5BSZYsA",
    url: "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=400&h=267&fit=crop",
    alt: "Electric vehicle charging station — transport electrification",
    pillar: "Pillar 1 – Operations",
    pillarNum: 1,
    subject: "EV charging station — transport electrification",
    composition: "human-scale",
    keywords: ["electric vehicle", "charging", "transport", "electrification", "fleet"],
    credit: "Chuttersnap",
  },

  // ── PILLAR 2: DECARBONISE VALUE CHAIN ─────────────────────────────────────
  {
    id: "ERI-VAL-001",
    unsplashId: "ZGjbiukp_-A",
    url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=267&fit=crop",
    alt: "Aerial view of a container port — global supply chain at scale",
    pillar: "Pillar 2 – Value Chain",
    pillarNum: 2,
    subject: "Container port aerial — global supply chain",
    composition: "aerial",
    keywords: ["port", "shipping", "supply chain", "logistics", "aerial"],
    credit: "Chuttersnap",
  },
  {
    id: "ERI-VAL-002",
    unsplashId: "3jBU9TbKW7o",
    url: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=400&h=267&fit=crop",
    alt: "Workers in a warehouse — supply chain operations and logistics",
    pillar: "Pillar 2 – Value Chain",
    pillarNum: 2,
    subject: "Warehouse workers — supply chain operations",
    composition: "human-scale",
    keywords: ["warehouse", "workers", "logistics", "supply chain", "operations"],
    credit: "Ruchindra Gunasekara",
  },
  {
    id: "ERI-VAL-003",
    unsplashId: "nGrfKmtwv24",
    url: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=267&fit=crop",
    alt: "Cargo ship at sea — maritime freight and emissions",
    pillar: "Pillar 2 – Value Chain",
    pillarNum: 2,
    subject: "Cargo ship at sea — maritime freight",
    composition: "wide",
    keywords: ["ship", "maritime", "freight", "cargo", "emissions"],
    credit: "Ian Taylor",
  },
  {
    id: "ERI-VAL-004",
    unsplashId: "jOqJbvo1P9g",
    url: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=400&h=267&fit=crop",
    alt: "Aerial view of a motorway with heavy goods vehicles — road freight",
    pillar: "Pillar 2 – Value Chain",
    pillarNum: 2,
    subject: "Motorway aerial with HGVs — road freight",
    composition: "aerial",
    keywords: ["motorway", "trucks", "freight", "road", "transport"],
    credit: "Denys Nevozhai",
  },
  {
    id: "ERI-VAL-005",
    unsplashId: "1K6IQsQbizI",
    url: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=400&h=267&fit=crop",
    alt: "Supplier meeting in a factory — supplier engagement and collaboration",
    pillar: "Pillar 2 – Value Chain",
    pillarNum: 2,
    subject: "Factory meeting — supplier engagement",
    composition: "human-scale",
    keywords: ["supplier", "meeting", "factory", "collaboration", "engagement"],
    credit: "Ant Rozetsky",
  },

  // ── PILLAR 3: BUILD & SCALE SOLUTIONS ─────────────────────────────────────
  {
    id: "ERI-SOL-001",
    unsplashId: "Q1p7bh3SHj8",
    url: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400&h=267&fit=crop",
    alt: "Offshore wind farm — scaling clean energy solutions",
    pillar: "Pillar 3 – Solutions",
    pillarNum: 3,
    subject: "Offshore wind farm — scaling clean energy",
    composition: "wide",
    keywords: ["offshore wind", "energy", "solutions", "scale", "clean"],
    credit: "Nicholas Doherty",
  },
  {
    id: "ERI-SOL-002",
    unsplashId: "hpjSkU2UYSU",
    url: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=400&h=267&fit=crop",
    alt: "Engineers working on a green technology prototype — innovation and solutions",
    pillar: "Pillar 3 – Solutions",
    pillarNum: 3,
    subject: "Engineers on green tech prototype — innovation",
    composition: "human-scale",
    keywords: ["engineers", "innovation", "technology", "prototype", "green"],
    credit: "Science in HD",
  },
  {
    id: "ERI-SOL-003",
    unsplashId: "8EzNkvLQosk",
    url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=267&fit=crop",
    alt: "Modern green office building — sustainable built environment",
    pillar: "Pillar 3 – Solutions",
    pillarNum: 3,
    subject: "Green office building — sustainable built environment",
    composition: "wide",
    keywords: ["building", "green", "sustainable", "architecture", "office"],
    credit: "Nastuh Abootalebi",
  },
  {
    id: "ERI-SOL-004",
    unsplashId: "SEnpTZwTPeU",
    url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=267&fit=crop",
    alt: "Circuit board close-up — digital and technology solutions",
    pillar: "Pillar 3 – Solutions",
    pillarNum: 3,
    subject: "Circuit board — digital technology solutions",
    composition: "human-scale",
    keywords: ["technology", "digital", "circuit", "innovation", "solutions"],
    credit: "Alexandre Debiève",
  },
  {
    id: "ERI-SOL-005",
    unsplashId: "Oja2ty_9ZLM",
    url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&h=267&fit=crop",
    alt: "Aerial view of a large solar installation — scaling renewable solutions",
    pillar: "Pillar 3 – Solutions",
    pillarNum: 3,
    subject: "Large solar installation aerial — scaling renewables",
    composition: "aerial",
    keywords: ["solar", "aerial", "scale", "renewable", "installation"],
    credit: "Zbynek Burival",
  },

  // ── PILLAR 4: MOBILISE FINANCE & INVESTMENT ───────────────────────────────
  {
    id: "ERI-FIN-001",
    unsplashId: "fiXLQXAhCfk",
    url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=267&fit=crop",
    alt: "Financial district aerial — capital markets and investment at scale",
    pillar: "Pillar 4 – Finance",
    pillarNum: 4,
    subject: "Financial district aerial — capital markets",
    composition: "aerial",
    keywords: ["finance", "investment", "capital", "markets", "aerial"],
    credit: "Maxim Hopman",
  },
  {
    id: "ERI-FIN-002",
    unsplashId: "s9CC2SKySJM",
    url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=267&fit=crop",
    alt: "Business meeting reviewing financial data — investment decision-making",
    pillar: "Pillar 4 – Finance",
    pillarNum: 4,
    subject: "Business meeting with financial data — investment decisions",
    composition: "human-scale",
    keywords: ["meeting", "finance", "data", "investment", "business"],
    credit: "Scott Graham",
  },
  {
    id: "ERI-FIN-003",
    unsplashId: "JKUTrJ4vK00",
    url: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=267&fit=crop",
    alt: "Green bond certificate and financial documents — sustainable finance",
    pillar: "Pillar 4 – Finance",
    pillarNum: 4,
    subject: "Financial documents — sustainable finance and green bonds",
    composition: "human-scale",
    keywords: ["green bonds", "sustainable finance", "documents", "investment", "ESG"],
    credit: "Markus Winkler",
  },
  {
    id: "ERI-FIN-004",
    unsplashId: "5fNmWej4tAA",
    url: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400&h=267&fit=crop",
    alt: "Aerial view of a city financial district at night — capital concentration",
    pillar: "Pillar 4 – Finance",
    pillarNum: 4,
    subject: "City financial district at night — capital concentration",
    composition: "aerial",
    keywords: ["city", "night", "financial", "aerial", "capital"],
    credit: "Maxim Hopman",
  },
  {
    id: "ERI-FIN-005",
    unsplashId: "IrRbSND5EUc",
    url: "https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?w=400&h=267&fit=crop",
    alt: "Analyst reviewing ESG investment data on screens — climate finance",
    pillar: "Pillar 4 – Finance",
    pillarNum: 4,
    subject: "ESG data analyst — climate finance and reporting",
    composition: "human-scale",
    keywords: ["ESG", "data", "analyst", "climate finance", "reporting"],
    credit: "Maxim Hopman",
  },

  // ── PILLAR 5: SHAPE POLICY & NARRATIVE ───────────────────────────────────
  {
    id: "ERI-POL-001",
    unsplashId: "Nv_QARcV1bA",
    url: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400&h=267&fit=crop",
    alt: "United Nations General Assembly hall — international policy and governance",
    pillar: "Pillar 5 – Policy",
    pillarNum: 5,
    subject: "UN General Assembly — international policy and governance",
    composition: "wide",
    keywords: ["UN", "policy", "governance", "international", "assembly"],
    credit: "Mathias Reding",
  },
  {
    id: "ERI-POL-002",
    unsplashId: "LqKhnDzSF-8",
    url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&h=267&fit=crop",
    alt: "Climate conference — policy makers and stakeholders in dialogue",
    pillar: "Pillar 5 – Policy",
    pillarNum: 5,
    subject: "Climate conference — policy dialogue",
    composition: "wide",
    keywords: ["conference", "climate", "policy", "dialogue", "stakeholders"],
    credit: "Pedro Lastra",
  },
  {
    id: "ERI-POL-003",
    unsplashId: "5QgIuuBxKwM",
    url: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=400&h=267&fit=crop",
    alt: "Government building facade — policy and regulatory frameworks",
    pillar: "Pillar 5 – Policy",
    pillarNum: 5,
    subject: "Government building — policy and regulatory frameworks",
    composition: "wide",
    keywords: ["government", "policy", "regulation", "building", "governance"],
    credit: "René DeAnda",
  },
  {
    id: "ERI-POL-004",
    unsplashId: "7okkFhxrxNw",
    url: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&h=267&fit=crop",
    alt: "Business leaders in a panel discussion — narrative and advocacy",
    pillar: "Pillar 5 – Policy",
    pillarNum: 5,
    subject: "Panel discussion — narrative and business advocacy",
    composition: "human-scale",
    keywords: ["panel", "discussion", "advocacy", "narrative", "leadership"],
    credit: "Campaign Creators",
  },
  {
    id: "ERI-POL-005",
    unsplashId: "9GocSmFiJF8",
    url: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&h=800&fit=crop",
    thumb: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=400&h=267&fit=crop",
    alt: "Roundtable meeting — multi-stakeholder policy engagement",
    pillar: "Pillar 5 – Policy",
    pillarNum: 5,
    subject: "Roundtable meeting — multi-stakeholder engagement",
    composition: "human-scale",
    keywords: ["roundtable", "meeting", "stakeholders", "policy", "engagement"],
    credit: "Headway",
  },
];

// Pillar colour map for gallery UI
export const pillarGalleryColors: Record<string, string> = {
  "Brand": "#3ba559",
  "Pillar 1 – Operations": "#6B8068",
  "Pillar 2 – Value Chain": "#00B8D4",
  "Pillar 3 – Solutions": "#3ba559",
  "Pillar 4 – Finance": "#F97316",
  "Pillar 5 – Policy": "#EF4444",
};

export const allPillars = [
  "Brand",
  "Pillar 1 – Operations",
  "Pillar 2 – Value Chain",
  "Pillar 3 – Solutions",
  "Pillar 4 – Finance",
  "Pillar 5 – Policy",
] as const;
