// AUTO-GENERATED — do not edit manually.
// Re-generated by scripts/gen-eri-version.mjs whenever @eri/components version changes.
// Source of truth: packages/eri-components/package.json
export const ERI_COMPONENTS_VERSION = "v2.16.1" as const;
